version: '3.9'

services:
  postgres:
    image: postgres:17.2-alpine
    environment:
      POSTGRES_USER: vnhope
      POSTGRES_PASSWORD: vnhope
      POSTGRES_DB: vnhope
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U vnhope']
      interval: 2s
      timeout: 5s
      retries: 5

  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    environment:
      DATABASE_URL: postgresql://vnhope:vnhope@postgres:5432/vnhope?sslmode=disable
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data:
